version: '3'

services:

  website:
    image: alexvarney/electionsmaster:latest
    container_name: ElectionsMaster-Node-server
    entrypoint: 'node server.js'
    expose:
      - "80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=electionsmaster.com
      - LETSENCRYPT_HOST=electionsmaster.com
      - LETSENCRYPT_EMAIL=alex@varney.me
      - HTTPS_METHOD=noredirect
    volumes:
      - /mnt/electionsmaster/assets:/mnt/electionsmaster/assets
    networks:
      - proxy
      - app
    links:
      - mongo

  mongo:
    expose:
      - "27017"
    image: mongo:3.4
    container_name: ElectionsMaster-mongodb
    volumes:
      - /var/lib/mongodb:/data/db
    networks:
      - app

networks:
  proxy:
    external:
      name: nginx-proxy
  app: